### ISSUE TITLE
Game?

### ISSUE THREAD

**Issue by JoaoGeniselli** [Alexandreobs/NarcoticosAnonimos#11]
https://github.com/Alexandreobs/NarcoticosAnonimos/blob/1fba23637bb34cb268e8de0c5d1dd9b537be8068/app/src/main/java/com/alexandreobsilva/a12passosnamauricio/view/adapter/AdapterDiario.kt#L30

Essa nomenclatura está certa: GameViewHolder?

Sugestão: alterar nomenclatura para algo que esteja no contexto do adapter.
Sendo ele um adapter de diário, penso que talvez um `DiarioViewHolder` ou, sei lá, `AnotacaoDiarioViewHolder`

**Comment by Alexandreobs** [comment]
correção de nomenclatura, usado AnotacaoDiarioViewHolder
