### ISSUE TITLE
Camel Case

### ISSUE THREAD

**Issue by JoaoGeniselli** [Alexandreobs/NarcoticosAnonimos#12]
https://github.com/Alexandreobs/NarcoticosAnonimos/blob/1fba23637bb34cb268e8de0c5d1dd9b537be8068/app/src/main/java/com/alexandreobsilva/a12passosnamauricio/view/fragments/DozepassosFragment.kt#L15

O nome de alguns fragments estão desobedecendo o camel-case.

**Comment by Alexandreobs** [comment]
Corrigido em todas as classes
