### ISSUE TITLE
Remover magic numbers

### ISSUE THREAD

**Issue by JoaoGeniselli** [Alexandreobs/NarcoticosAnonimos#2]
https://github.com/Alexandreobs/NarcoticosAnonimos/blob/ab92a26e1efcc22ab015e930f5d631b88876e05d/app/src/main/java/com/alexandreobsilva/a12passosnamauricio/view/activitys/DetalheActivity.kt#L33

Os "getSerializable"s estão procurando chaves que não descrevem o real propósito o valor armazenado. São como "Magic numbers".

Veja abaixo um link como lidar com isso e refatorar:
https://refactoring.guru/replace-magic-number-with-symbolic-constant#:~:text=A%20magic%20number%20is%20a,program%20and%20refactor%20the%20code.

**Comment by Alexandreobs** [comment]
magic number refatorado
